/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author kpach
 */
public class Assign_page extends javax.swing.JFrame {

       private java.sql.Connection con;     
    public Assign_page() {
        initComponents();
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "system", "root1234");
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Failed to connect to the database: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }//
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtuser = new javax.swing.JTextField();
        jtuser3 = new javax.swing.JTextField();
        jtuser4 = new javax.swing.JTextField();
        jtuser5 = new javax.swing.JTextField();
        blogin = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Username");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Developer_id");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtuser.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        jtuser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtuserActionPerformed(evt);
            }
        });
        getContentPane().add(jtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 540, 40));

        jtuser3.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        jtuser3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jtuser3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtuser3ActionPerformed(evt);
            }
        });
        getContentPane().add(jtuser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 540, 40));

        jtuser4.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        jtuser4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jtuser4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtuser4ActionPerformed(evt);
            }
        });
        getContentPane().add(jtuser4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 540, 40));

        jtuser5.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        jtuser5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jtuser5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtuser5ActionPerformed(evt);
            }
        });
        getContentPane().add(jtuser5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 540, 40));

        blogin.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        blogin.setText("Submit");
        blogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        blogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloginActionPerformed(evt);
            }
        });
        getContentPane().add(blogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 590, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Click here to new account (4).png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtuserActionPerformed

    private void bloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloginActionPerformed

//        System.out.println(dev_id);
//                System.out.println(dev_email);
//        System.out.println(bug_id);
//        System.out.println(bug_name);

        if(jtuser3.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill out Developer's id!!");
        }
        if(jtuser5.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill out Bug id!!");
        }
        if(jtuser.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill out Bug name!!");
        }
        if(jtuser4.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill out developer email!!");
        }

        else{
            try{        
String dev_id=jtuser3.getText();
        String dev_email=jtuser4.getText();
        String bug_id=jtuser5.getText();
        String bug_name=jtuser.getText();
        String query = "insert into assign values(?,?,?,?)";
        PreparedStatement pstmt = con.prepareStatement(query);
        
        pstmt.setString(1, dev_id);
        pstmt.setString(2, bug_id);
                pstmt.setString(3, bug_name);
        pstmt.setString(4, dev_email);

        ResultSet rs = pstmt.executeQuery();
                    JOptionPane.showMessageDialog(null, "Successful Assigned");
        dashboarddeveloper dash = new dashboarddeveloper();
        dash.setVisible(true);
        dash.pack();
        dash.setLocationRelativeTo(null);
        //rgf.setDefaultCloseOpertaion(JFrame.EXIT_ON_CLOSE);
        this.dispose();

        // Close resources
//        pstmt.close();
//        rs.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "An error occurred while attempting to log in: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
        }
        //        String user=jtuser.getText();
        //        String password=jpassword.getText();
        //
        //        System.out.println("user"+user+"password:"+password);
    }//GEN-LAST:event_bloginActionPerformed

    private void jtuser3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtuser3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtuser3ActionPerformed

    private void jtuser4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtuser4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtuser4ActionPerformed

    private void jtuser5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtuser5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtuser5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Assign_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Assign_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Assign_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Assign_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Assign_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton blogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jtuser;
    private javax.swing.JTextField jtuser3;
    private javax.swing.JTextField jtuser4;
    private javax.swing.JTextField jtuser5;
    // End of variables declaration//GEN-END:variables
}
