/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import javax.swing.RowFilter;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author kpach
 */
public class BugsRecords_page extends javax.swing.JFrame {
    private Connection con;
        private JTable bugTable;
    private DefaultTableModel tableModel;
    private JTextArea textArea;
    private JButton generateButton;
    private JButton downloadButton;

    /**
     * Creates new form BugsRecords_page
     * @throws java.io.FileNotFoundException
     */
    public BugsRecords_page() throws FileNotFoundException {
         initComponents();
        getContentPane().setLayout(new BorderLayout());
         setTitle("Closed Bugs Report");
        setSize(800, 900);
                
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        textArea = new JTextArea();
        textArea.setEditable(false);

        // Initialize table model and table
        tableModel = new DefaultTableModel();
        bugTable = new JTable(tableModel);

        // Set column headers
        tableModel.addColumn("Bug ID");
        tableModel.addColumn("Bug Title");
        tableModel.addColumn("Bug Type");
        tableModel.addColumn("Bug Status");

        // Add table to a scroll pane
        JScrollPane scrollPane = new JScrollPane(bugTable);

        // Add scroll pane to the center of the frame
        getContentPane().add(scrollPane, BorderLayout.CENTER);

        // Create panel to hold the table at the bottom
        JPanel bottomPanel = new JPanel(new FlowLayout(FlowLayout.CENTER));
        bottomPanel.add(scrollPane); // Add scroll pane to the panel

        // Add the panel to the bottom of the frame
        getContentPane().add(bottomPanel, BorderLayout.NORTH);
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "system", "root1234");
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Failed to connect to the database: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }// 
        try{
        String query="select bug_id,bug_title,bug_desc,bug_type,bug_status,posted_at from bugs";
        PreparedStatement statement =con.prepareStatement(query);
        ResultSet rs=statement.executeQuery();
//        Document document = new Document();
//        PdfWriter.getInstance(document, new FileOutputStream("closed_bugs_report.pdf"));
//                document.open();
//
//                // Add title and header
//                document.add(new Paragraph("Closed Bugs Report\n"));
//                document.add(new Paragraph("List of Bugs Closed in the System:\n"));
        
        while(rs.next()){
            String bugTitle=rs.getString("bug_title");
            int bugId=rs.getInt("bug_id");
            String bugDesc=rs.getString("bug_desc");
            String bugType=rs.getString("bug_type");
            String bugStatus=rs.getString("bug_status");
            String postedAt=rs.getString("posted_at");
            
            tableModel.addRow(new Object[]{bugId,bugTitle,bugType, bugStatus});
            
            
        }

        }catch(SQLException e){
        }
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtuser3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("BUGS RECORDS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Search Record");

        jtuser3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtuser3ActionPerformed(evt);
            }
        });
        jtuser3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtuser3KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtuser3, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(335, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jtuser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(489, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtuser3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtuser3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtuser3ActionPerformed

    private void jtuser3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtuser3KeyPressed
        // TODO add your handling code here:
//        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(tableModel);
bugTable.setRowSorter(sorter);
sorter.setRowFilter(RowFilter.regexFilter(jtuser3.getText()));

    }//GEN-LAST:event_jtuser3KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BugsRecords_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BugsRecords_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BugsRecords_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BugsRecords_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    new BugsRecords_page().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(BugsRecords_page.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jtuser3;
    // End of variables declaration//GEN-END:variables
}
