/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import javax.swing.RowFilter;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
//import com.itextpdf.text.Document;
//import com.itextpdf.text.Paragraph;
//import com.itextpdf.text.pdf.PdfWriter;
//import java.io.FileOutputStream;

/**
 *
 * @author kpach
 */
public class BugsRecords_page extends javax.swing.JFrame {
    private Connection con;
        private JTable bugTable;
    private DefaultTableModel tableModel;
    private JTextArea textArea;

    /**
     * Creates new form BugsRecords_page
     */
    public BugsRecords_page() {
         initComponents();
        getContentPane().setLayout(new BorderLayout());
         setTitle("Closed Bugs Report");
        setSize(400, 300);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        textArea = new JTextArea();
        textArea.setEditable(false);

        // Initialize table model and table
        tableModel = new DefaultTableModel();
        bugTable = new JTable(tableModel);

        // Set column headers
        tableModel.addColumn("Bug ID");
        tableModel.addColumn("Bug Title");
        tableModel.addColumn("Bug Type");
        tableModel.addColumn("Bug Status");

        // Add table to a scroll pane
        JScrollPane scrollPane = new JScrollPane(bugTable);

        // Add scroll pane to the center of the frame
        getContentPane().add(scrollPane, BorderLayout.CENTER);

        // Create panel to hold the table at the bottom
        JPanel bottomPanel = new JPanel(new FlowLayout(FlowLayout.CENTER));
        bottomPanel.add(scrollPane); // Add scroll pane to the panel

        // Add the panel to the bottom of the frame
        getContentPane().add(bottomPanel, BorderLayout.SOUTH);
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "system", "root1234");
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Failed to connect to the database: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }// 
        try{
        String query="select bug_id,bug_title,bug_type,bug_status from bugs";
        PreparedStatement statement =con.prepareStatement(query);
        ResultSet rs=statement.executeQuery();
//        PdfWriter.getInstance(document, new FileOutputStream("closed_bugs_report.pdf"));
//                document.open();
//
//                // Add title and header
//                document.add(new Paragraph("Closed Bugs Report\n"));
//                document.add(new Paragraph("List of Bugs Closed in the System:\n"));
//        
        while(rs.next()){
            String bugTitle=rs.getString("bug_title");
            int bugId=rs.getInt("bug_id");
            String bugType=rs.getString("bug_type");
            String bugStatus=rs.getString("bug_status");
            
            tableModel.addRow(new Object[]{bugId,bugTitle,bugType, bugStatus});
//            document.add(new Paragraph("Bug Title: " + bugTitle));
//                    document.add(new Paragraph("Description: " + bugDesc));
//                    document.add(new Paragraph("Type: " + bugType));
//                    document.add(new Paragraph("Posted At: " + postedAt));
//                    document.add(new Paragraph("\n"));

            
        }
        }catch(SQLException e){
            e.printStackTrace();
        }
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        bg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1148, 861, 218, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 48)); // NOI18N
        jLabel6.setText("BUG RECORDS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 410, 70));

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 40)); // NOI18N
        jLabel1.setText("Search Records");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jTextField1.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 450, 50));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Click here to new account (5).png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BugsRecords_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BugsRecords_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BugsRecords_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BugsRecords_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new BugsRecords_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
